# docker-compose.yml
version: "3"
services:
  server:
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server/src:/srv/app/fr-shoin-admin-server/src
    command: npm run dev

  client:
    build: ./client
    environment:
      REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/src:/srv/app/fr-shoin-admin-client/src
      - ./client/src:/srv/app/fr-shoin-admin-client/public
    links:
      - server
    command: npm run start